### ISSUE TITLE
Error when accessing wheelhouse.odoo-community.org

### ISSUE THREAD

**Issue by em230418** [OCA/oca-ci#75]
In one of my private github repositories "test on Odoo" workflow failed on step "Install addons and dependencies". Here are cutted logs:

```
+ pip install -r test-requirements.txt -c test-constraints.txt
WARNING: The directory '/github/home/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
Looking in indexes: https://wheelhouse.odoo-community.org/oca-simple-and-pypi
Collecting git+https://github.com/itpp-labs/sync-addons@15.0#subdirectory=setup/sync (from -r test-requirements.txt (line 2))
  Cloning https://github.com/itpp-labs/sync-addons (to revision 15.0) to /tmp/pip-req-build-pxtnbmsh
  Running command git clone --filter=blob:none --quiet https://github.com/itpp-labs/sync-addons /tmp/pip-req-build-pxtnbmsh
  Running command git checkout -b 15.0 --track origin/15.0
  Switched to a new branch '15.0'
  Branch '15.0' set up to track remote branch '15.0' from 'origin'.
  Resolved https://github.com/itpp-labs/sync-addons to commit 84345c4798eb28cce1bc11e89f3cdcad0b5e76b7
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [53 lines of output]
      WARNING: The directory '/github/home/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
      WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)'))': /oca-simple-and-pypi/setuptools-odoo/
      WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)'))': /oca-simple-and-pypi/setuptools-odoo/
      WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)'))': /oca-simple-and-pypi/setuptools-odoo/
      WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)'))': /oca-simple-and-pypi/setuptools-odoo/
      WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)'))': /oca-simple-and-pypi/setuptools-odoo/
      ERROR: Could not find a version that satisfies the requirement setuptools-odoo (from versions: none)
      ERROR: No matching distribution found for setuptools-odoo
      /opt/odoo-venv/lib/python3.8/site-packages/setuptools/__init__.py:80: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!
      
              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************
      
      !!
        dist.fetch_build_eggs(dist.setup_requires)
      Traceback (most recent call last):
        File "/opt/odoo-venv/lib/python3.8/site-packages/setuptools/installer.py", line 101, in _fetch_build_egg_no_warn
          subprocess.check_call(cmd)
        File "/usr/lib/python3.8/subprocess.py", line 3[64](https://github.com/it-projects-llc/**REDACTED**/actions/runs/10501374778/job/29091253886#step:5:65), in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/opt/odoo-venv/bin/python3.8', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpzp0rmq11', '--quiet', 'setuptools-odoo']' returned non-zero exit status 1.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-pxtnbmsh/setup/sync/setup.py", line 3, in <module>
          setuptools.setup(
        File "/opt/odoo-venv/lib/python3.8/site-packages/setuptools/__init__.py", line 102, in setup
          _install_setup_requires(attrs)
        File "/opt/odoo-venv/lib/python3.8/site-packages/setuptools/__init__.py", line [75](https://github.com/it-projects-llc/**REDACTED**/actions/runs/10501374778/job/29091253886#step:5:76), in _install_setup_requires
          _fetch_build_eggs(dist)
        File "/opt/odoo-venv/lib/python3.8/site-packages/setuptools/__init__.py", line 80, in _fetch_build_eggs
          dist.fetch_build_eggs(dist.setup_requires)
        File "/opt/odoo-venv/lib/python3.8/site-packages/setuptools/dist.py", line 641, in fetch_build_eggs
          return _fetch_build_eggs(self, requires)
        File "/opt/odoo-venv/lib/python3.8/site-packages/setuptools/installer.py", line 38, in _fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/opt/odoo-venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line [78](https://github.com/it-projects-llc/***REDACTED**/actions/runs/10501374778/job/29091253886#step:5:79)7, in resolve
          dist = self._resolve_dist(
        File "/opt/odoo-venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 823, in _resolve_dist
          dist = best[req.key] = env.best_match(
        File "/opt/odoo-venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1093, in best_match
          return self.obtain(req, installer)
        File "/opt/odoo-venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1104, in obtain
          return installer(requirement) if installer else None
        File "/opt/odoo-venv/lib/python3.8/site-packages/setuptools/installer.py", line 103, in _fetch_build_egg_no_warn
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['/opt/odoo-venv/bin/python3.8', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpzp0rmq11', '--quiet', 'setuptools-odoo']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```

Looks file problems with certificate in https://wheelhouse.odoo-community.org/
At the moment it returns text "Circulez, bonnes gens!" on any subdirectory.

**Comment by em230418** [comment]
04:02:52 GMT. IP was 37.27.127.84
```
$ curl -k https://wheelhouse.odoo-community.org/ -v
* Host wheelhouse.odoo-community.org:443 was resolved.
* IPv6: 2a01:4f9:3070:3164::2
* IPv4: 37.27.127.84
*   Trying 37.27.127.84:443...
* Connected to wheelhouse.odoo-community.org (37.27.127.84) port 443
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384 / [blank] / UNDEF
* ALPN: server accepted http/1.1
* Server certificate:
*  subject: CN=Debian-bookworm-latest-amd64-base
*  start date: Jun 22 14:53:31 2024 GMT
*  expire date: Jun 20 14:53:31 2034 GMT
*  issuer: CN=Debian-bookworm-latest-amd64-base
*  SSL certificate verify result: self signed certificate (18), continuing anyway.
*   Certificate level 0: Public key type ? (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
* using HTTP/1.x
> GET / HTTP/1.1
> Host: wheelhouse.odoo-community.org
> User-Agent: curl/8.7.1
> Accept: */*
> 
* Request completely sent off
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
< HTTP/1.1 200 OK
< Server: nginx/1.22.1
< Date: Thu, 22 Aug 2024 04:02:52 GMT
< Content-Type: application/octet-stream
< Content-Length: 22
< Connection: keep-alive
< Content-Type: text/plain
< 
* Connection #0 to host wheelhouse.odoo-community.org left intact
Circulez, bonnes gens!
```

2 hours later different IP address, but probably(!) legit response.
```
$ curl -v https://wheelhouse.odoo-community.org/
* Host wheelhouse.odoo-community.org:443 was resolved.
* IPv6: 2a01:4f8:a0:430d::2
* IPv4: 85.10.204.136
*   Trying 85.10.204.136:443...
* Connected to wheelhouse.odoo-community.org (85.10.204.136) port 443
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /usr/share/ca-certificates/ca-bundle.crt
*  CApath: none
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-ECDSA-AES256-GCM-SHA384 / [blank] / UNDEF
* ALPN: server accepted http/1.1
* Server certificate:
*  subject: CN=odoo-community.org
*  start date: Jun 23 14:52:46 2024 GMT
*  expire date: Sep 21 14:52:45 2024 GMT
*  subjectAltName: host "wheelhouse.odoo-community.org" matched cert's "wheelhouse.odoo-community.org"
*  issuer: C=US; O=Let's Encrypt; CN=E5
*  SSL certificate verify ok.
*   Certificate level 0: Public key type ? (256/128 Bits/secBits), signed using ecdsa-with-SHA384
*   Certificate level 1: Public key type ? (384/192 Bits/secBits), signed using sha256WithRSAEncryption
*   Certificate level 2: Public key type ? (4096/128 Bits/secBits), signed using sha256WithRSAEncryption
* using HTTP/1.x
> GET / HTTP/1.1
> Host: wheelhouse.odoo-community.org
> User-Agent: curl/8.7.1
> Accept: */*
> 
* Request completely sent off
< HTTP/1.1 200 OK
< Server: nginx/1.14.2
< Date: Thu, 22 Aug 2024 06:04:06 GMT
< Content-Type: text/html
< Content-Length: 655
< Last-Modified: Sun, 23 Jun 2024 16:11:34 GMT
< Connection: keep-alive
< ETag: "66784936-28f"
< Expires: Thu, 22 Aug 2024 07:04:06 GMT
< Cache-Control: max-age=3600
< Cache-Control: public
< Accept-Ranges: bytes
< 
<html>
  <head>
    <title>wheelhouse.odoo-community.org</title>
  </head>
  <body>
    <h1>Welcome to wheelhouse.odoo-community.org</h1>
    <p>This is a repository of python <a href="https://pypi.python.org/pypi/wheel">wheels</a> 
       for all <a href="https://odoo-community.org">OCA</a> addons.
    <p>You can use pip with --index-url=https://wheelhouse.odoo-community.org/oca-simple-and-pypi to obtain OCA addons from here, and all other packages from PyPI, effectively masking non-OCA addons that are on PyPI.</p>
    <p>For help and support, email <a href="mailto:support@odoo-community.org">support@odoo-community.org</a>.</p>
  </body>
</head>
* Connection #0 to host wheelhouse.odoo-community.org left intact
```

**Comment by nilshamerlinck** [comment]
Hello @em230418 there was indeed a DNS issue that has been fixed by Stéphane Bidoul meanwhile. Did you join the OCA discord already? The channel `#oca-infrastructure` is handy for this type of event.

**Comment by em230418** [comment]
> Did you join the OCA discord already?

Just joined it. Thanks for info!

Restarted job, looks fine.
